### ISSUE TITLE
Access to ipSegments $refs

### ISSUE THREAD

**Issue by jamie-kount** [peteringram0/vue-ip#5]
I am using vue-ip for an IP address range component where I need to verify the second ip address is greater than the first ip address. In order to do this, I need access to the segments within each ip address. Could this possibly be added as a parameter to the on-change event?

**Comment by peteringram0** [comment]
@jamie-kount the onChange event sends back the the IP. You can simply run a .split('.') against it to get it as an array then compare each segment or something similar?
